### PR TITLE
Updated README.md

### LINKED ISSUE #6: Add unlicense
https://unlicense.org/

### PR DESCRIPTION
**Pull request by merrcury**
## Description of new feature, or changes
Added Unlicense.org to the readme. So, No one should look for Issue/PR, if this project contains it or not, again. 

## Checklist

- [X] Your branch is up-to-date with the base branch
- [X] You've included at least one test if this is a new feature
- [X] All tests are passing

## Related Issues and Discussions

Fixes #6

### CODE REVIEW

**Comment by plibither8** [comment]
Thanks for this. I just noticed that the Unlicense file - https://github.com/plibither8/licensed/blob/master/assets/Unlicense - is not present in the `assets/licenses` directory, but in `assets/`.

It would be great if you could move the file to the `assets/licenses` directory to prevent the app from breaking/crashing.

**Comment by plibither8** [comment]
Thanks!

**Comment by merrcury** [comment]
I moved the Unlicense file.

**Comment by plibither8** [comment]
Merged :)

**Pull request merged**
